#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

case `uname` in
  # bug on Windows/Github Desktop: add `.cmd` extension fixes it
  *CYGWIN*|*MINGW*|*MSYS*)
    npx.cmd lint-staged
  ;;
  *)
    npx lint-staged
  ;;
esac
