name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # 403 Forbidden error on changelogithub

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm config set registry https://registry.npmmirror.com
      - run: pnpm i
      - run: pnpm build
      - run: npx jsr publish

      - run: npm publish --registry=https://registry.npmjs.org --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: pnpm sync-to-cnpm
        if: success()
